apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-html-deployment #Nome do Deployment
  labels:
    app: app-html #Nome do Aplicativo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-html # Mesmo valor de Labels->app
  template: 
    metadata:
      labels:
        app: app-html # Mesmo valor de Labels->app
    spec: 
      containers:
      - name: app-html
        image: nginx:latest
        ports:
        - containerPort: 80